Add curl to the image to allow integration of scripts that use webhooks without modifying the base image.
Icinga/docker-icinga2 pull request #55
Opened 2021-03-02 10:41 UTC by dwt

I found that many scripts to trigger web hooks require curl.

For example to trigger a notification in Telegram, a curl comand like this is required:

/usr/bin/curl --silent --output /dev/null --data-urlencode chat_id=$chat_id --data-urlencode "text=$notification_text" --data-urlencode parse_mode=HTML --data-urlencode disable_web_page_preview=true https://api.telegram.org/$bot_id/sendMessage

Also the ca-certificates package was added, to allow validating certificates.

2021-03-02 10:44 UTC, dwt commented
ca-certificates are also required for #52 so I guess that is uncontroversial. curl adds about 400kb to the final image size.

I would hope that this is an acceptable tradeoff to allow integration of many web hook based services without having to derive an image from the base image.

2021-03-02 14:17 UTC, julianbrost requested changes
This now needs resolving conflicts now due to #50 being merged. Apart from that, I think it's fine.

2021-03-02 14:21 UTC, Al2Klimov commented
*Sigh*.. I **intentionally** didn’t mention this before #52 not to let the author rebase twice.

2021-03-03 12:11 UTC, dwt commented
@N-o-X @Al2Klimov rebased and ready to merge. I'd love some feedback if possible.

2021-03-03 12:11 UTC, Al2Klimov approved these changes

2021-03-03 12:12 UTC, N-o-X approved these changes

2021-03-03 12:19 UTC, N-o-X commented
Sorry for those rebases, didn't have this PR in mind.

I'll merge this, once the build is done.

Thanks for contributing!

2021-03-03 12:35 UTC, dwt commented
@N-o-X Since I haven't found out yet, how often do you release image changes to the docker hub?

2021-03-03 12:35 UTC, merged

2021-03-03 12:36 UTC, Al2Klimov commented
Master (snapshot): once every master commit
Release: once every upstream release

2021-03-03 13:43 UTC, dwt commented
thx